<!DOCTYPE html>
<html lang="en">
<head>
    <title>PRAKIRAAN INTENSITAS CURAH HUJAN DI SURABAYA</title>
</head>
<body>
    <script>
        var prakirahujan = prompt("Status intensitas hujan di surabaya?", 0);

        if(prakirahujan > 300){
            document.write("<h2>WASPADA!!!!!! HUJAN LEBAT HINDARI BERTEDUH DI BAWAH POHON!!!</h2>");
        } else {
            document.write("<p>HUJAN SEDANG!!!, JAGA DIRI BAIK-BAIK!!!! !!!</p>");
        }
        document.write("<p>BY PROKOM KELOMPOK 2  </p>");
    </script>
</body>
</html>  